pub const KEYWORDS: &'static [&'static str; 23] = &[
    "if", "else", "for", "fn", "in", "of", "match", "loop", "case", "from", "as", "do", "while",
    "break", "continue", "return", "crash", "try", "recover", "println", "readonly", "static",
    "sleep",
];
pub const INJUNCTIONS: &'static [&'static str; 14] = &[
    "implement",
    "interface",
    "model",
    "public",
    "specify",
    "record",
    "const",
    "let",
    "enum",
    "function",
    "type",
    "use",
    "prepend",
    "test",
];
#[derive(Debug, Clone, PartialEq)]
pub enum Keyword {
    For,
    If,
    Else,
    Fn,
    In,
    Match,
    Loop,
    Case,
    Break,
    From,
    As,
    Do,
    While,
    Continue,
    Return,
    Crash,
    Try,
    Recover,
    Println,
    Sleep,
    Static,
    Injunction(Injunction),
}
#[derive(Debug, Clone, PartialEq)]
pub enum Injunction {
    Function,
    Type,
    Model,
    Record,
    Const,
    Let,
    Use,
    Prepend,
    Test,
    Enum,
    Interface,
    Implement,
    Specify,
    Public,
}
